#include "main.h"

extern void SysTick_Handler(void);

int main(void)
{
	SET_BIT(SYSTEM_CTRL_RCGCGPIO_R.B.PORTF_CLK);
	
	SET_BIT_FIELD_VALUE(GPIO_PORTF_GPIODEN_R.B.DEN, GPIO_PF3_ENABLE);
	
	SET_BIT_FIELD_VALUE(GPIO_PORTF_GPIODIR_R.B.DIR, GPIO_PF3_ENABLE);
	
	
	SET_BIT_FIELD_VALUE(CORE_PPH_STCURRENT_R.B.CURRENT, 0x0);
	
	SET_BIT_FIELD_VALUE(CORE_PPH_STRELOAD_R.B.RELOAD, 15999999);
	
	SET_BIT(CORE_PPH_STCTRL_R.B.CLK_SRC);
	
	SET_BIT(CORE_PPH_STCTRL_R.B.INTEN);
	
	SET_BIT(CORE_PPH_STCTRL_R.B.ENABLE);
	
	/* Super Loop */
	while(1)
		{
			//SET_BIT_FIELD_VALUE(GPIO_PORTF_GPIODATA_R.B.DATA, GPIO_PF3_ENABLE);
		}
}

void SysTick_Handler(void)
{
	GPIO_PORTF_GPIODATA_R.B.DATA ^= GPIO_PF3_ENABLE;
}
